# 起動
# docker-compose up -d # 両方起動
# docker-compose up -d pgsql_study # postgresql 起動
# docker-compose up -d mysql_study # mysql 起動
# 接続
# psql -h 127.0.0.1 -U dev -d shop # postgresql 接続
# mysql -h 127.0.0.1 -u dev -p -d shop # mysql 接続

version: "3"

services:
  pgsql_study:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: secret
    volumes:
      - ./pgsql_db:/var/lib/postgresql/data
    container_name: pgsql_study
  mysql_study:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: dev
      MYSQL_PASSWORD: secret
    volumes:
      - ./mysql_db:/var/lib/mysql
    container_name: mysql_study